export const strings = {
    joinCount: 'Количество входов на сервер',
    chatMessagesCount: 'Отправлено сообщений в чат',
    playerDeathCount: 'Количество смертей',
    blockBreaksCount: 'Блоков разрушено',
    placedBlocksCount: 'Блоков установлено',
    entitiesKillsCount: 'Существ убито',
    breedAnimalsCount: 'Животных разведено',
    extractFurnaceCount: 'Переработано в печи',
    fishingCount: 'Поймано удочкой',
    enchantItemsCount: 'Зачаровано предметов',
    uniquePlayersCount: 'Количество уникальных игроков',

    squid: 'Спрут',
    creeper: 'Крипер',
    phantom: 'Фантом',
    zombie: 'Зомби',
    drowned: 'Утопленний',
    skeleton: 'Скелет',
    spider: 'Паук',
    salmon: 'Лосось',
    sheep: 'Овца',
    pig: 'Свинья',
    cow: 'Корова',
    chicken: 'Курица',
    cod: 'Треска',
    llama: 'Лама',
    rabbit: 'Кролик',
    husk: 'Кадавр',
    iron_golem: 'Железный голем',
    zombie_villager: 'Зомби житель',
    witch: 'Ведьма',
    bat: 'Летучая мышь',
    horse: 'Лошадь',
    donkey: 'Осёл',
    pillager: 'Разбойник',
    cave_spider: 'Пещерный паук',
    bee: 'Пчела',
    blaze: 'Сполох',
    wither_skeleton: 'Скеле иссушитель',
    magma_cube: 'Лавовый куб',
    enderman: 'Странник края',
    skeleton_horse: 'Лошадь скелет',
    zombie_pigman: 'Зомби свиночеловек',
    villager: 'Житель',
    ghast: 'Гаст',
    silverfish: 'Чешуйница',
    wolf: 'Волк',
    slime: 'Слизень',
    fox: 'Лиса',
    turtle: 'Черепаха',
    cat: 'Кошка',
    trader_llama: 'Странствующий торговец',
    tropical_fish: 'Тропческая рыба',
    parrot: 'Попугай',
    panda: 'Панда',
    stray: 'Зимогор',
    ender_dragon: 'Дракон края',
    shulker: 'Шалкер',
    polar_bear: 'Белый медведь',
    ravager: 'Разоритель',
    vindicator: 'Поборник',
    vex: 'Досаждатель',
    evoker: 'Призыватель',
}