/* eslint-disable */

import config from 'config';

const strings = {
  joinCount: 'Количество входов на сервер',
  chatMessagesCount: 'Отправлено сообщений в чат',
  playerDeathCount: 'Количество смертей',
  blockBreaksCount: 'Блоков разрушено',
  placedBlocksCount: 'Блоков установлено',
  entitiesKillsCount: 'Существ убито',
  breedAnimalsCount: 'Животных разведено',
  extractFurnaceCount: 'Переработано в печи',
  fishingCount: 'Поймано удочкой',
  enchantItemsCount: 'Зачаровано предметов',
  uniquePlayersCount: 'Количество уникальных игроков',

  squid: 'Спрут',
  creeper: 'Крипер',
  phantom: 'Фантом',
  zombie: 'Зомби',
  drowned: 'Утопленник',
  skeleton: 'Скелет',
  spider: 'Паук',
  salmon: 'Лосось',
  sheep: 'Овца',
  pig: 'Свинья',
  cow: 'Корова',
  chicken: 'Курица',
  cod: 'Треска',
  llama: 'Лама',
  rabbit: 'Кролик',
  husk: 'Кадавр',
  iron_golem: 'Железный голем',
  zombie_villager: 'Зомби житель',
  witch: 'Ведьма',
  bat: 'Летучая мышь',
  horse: 'Лошадь',
  donkey: 'Осёл',
  pillager: 'Разбойник',
  cave_spider: 'Пещерный паук',
  bee: 'Пчела',
  blaze: 'Сполох',
  wither_skeleton: 'Скеле иссушитель',
  magma_cube: 'Лавовый куб',
  enderman: 'Странник края',
  skeleton_horse: 'Лошадь скелет',
  zombie_pigman: 'Зомби свиночеловек',
  villager: 'Житель',
  ghast: 'Гаст',
  silverfish: 'Чешуйница',
  wolf: 'Волк',
  slime: 'Слизень',
  fox: 'Лиса',
  turtle: 'Черепаха',
  cat: 'Кошка',
  trader_llama: 'Странствующий торговец',
  tropical_fish: 'Тропческая рыба',
  parrot: 'Попугай',
  panda: 'Панда',
  stray: 'Зимогор',
  ender_dragon: 'Дракон края',
  shulker: 'Шалкер',
  polar_bear: 'Белый медведь',
  ravager: 'Разоритель',
  vindicator: 'Поборник',
  vex: 'Досаждатель',
  evoker: 'Призыватель',
  wither: 'Иссушитель',
  snow_golem: 'Снежный голем',
  wandering_trader: 'Странствующий торговец',
  dolphin: 'Дельфин',

  'minecraft:acacia_button': 'Акациевая кнопка',
  'minecraft:acacia_door': 'Акациевая дверь',
  'minecraft:acacia_fence': 'Акациевый забор',
  'minecraft:acacia_fence_gate': 'Акациевая калитка',
  'minecraft:acacia_leaves': 'Листья акации',
  'minecraft:acacia_log': 'Акациевое бревно',
  'minecraft:acacia_planks': 'Акациевые доски',
  'minecraft:acacia_pressure_plate': 'Акациевая нажимная плита',
  'minecraft:acacia_sapling': 'Саженец акации',
  'minecraft:acacia_sign': 'Акациевая табличка',
  'minecraft:acacia_slab': 'Акациевая плита',
  'minecraft:acacia_stairs': 'Акациевые ступеньки',
  'minecraft:acacia_trapdoor': 'Акациевый люк',
  'minecraft:acacia_wall_sign': 'Акациевая настенная табличка',
  'minecraft:acacia_wood': 'Акация',
  'minecraft:activator_rail': 'Активирующие рельсы',
  'minecraft:air': 'Воздух',
  'minecraft:allium': 'Лук-батун',
  'minecraft:andesite': 'Андезит',
  'minecraft:andesite_slab': 'Андезитовая плита',
  'minecraft:andesite_stairs': 'Андезитовые ступеньки',
  'minecraft:andesite_wall': 'Андезитовая ограда',
  'minecraft:anvil': 'Наковальня',
  'minecraft:attached_melon_stem': 'Прикреплённый стебель арбуза',
  'minecraft:attached_pumpkin_stem': 'Прикреплённый стебель тыквы',
  'minecraft:azure_bluet': 'Хаустония серая',
  'minecraft:bamboo': 'Бамбук',
  'minecraft:bamboo_sapling': 'Саженец бамбука',
  'minecraft:barrel': 'Бочка',
  'minecraft:barrier': 'Барьер',
  'minecraft:beacon': 'Маяк',
  'minecraft:beacon.primary': 'Основной эффект',
  'minecraft:beacon.secondary': 'Вторичный эффект',
  'minecraft:bed': 'Кровать',
  'minecraft:bed.no_sleep': 'Вы можете спать только ночью и во время грозы',
  'minecraft:bed.not_safe': 'Вы не можете уснуть, пока рядом есть монстры',
  'minecraft:bed.not_valid': 'Ваша кровать пропала или доступ к ней затруднён',
  'minecraft:bed.obstructed': 'Эта кровать заблокирована',
  'minecraft:bed.occupied': 'Эта кровать занята',
  'minecraft:bed.set_spawn': 'Точка возрождения установлена',
  'minecraft:bed.too_far_away': 'Вы не можете уснуть, кровать слишком далеко',
  'minecraft:bedrock': 'Бедрок',
  'minecraft:bee_nest': 'Пчелиное гнездо',
  'minecraft:beehive': 'Улей',
  'minecraft:beetroots': 'Свёкла',
  'minecraft:bell': 'Колокол',
  'minecraft:birch_button': 'Берёзовая кнопка',
  'minecraft:birch_door': 'Берёзовая дверь',
  'minecraft:birch_fence': 'Берёзовый забор',
  'minecraft:birch_fence_gate': 'Берёзовая калитка',
  'minecraft:birch_leaves': 'Берёзовые листья',
  'minecraft:birch_log': 'Берёзовое бревно',
  'minecraft:birch_planks': 'Берёзовые доски',
  'minecraft:birch_pressure_plate': 'Берёзовая нажимная плита',
  'minecraft:birch_sapling': 'Саженец берёзы',
  'minecraft:birch_sign': 'Берёзовая табличка',
  'minecraft:birch_slab': 'Берёзовая плита',
  'minecraft:birch_stairs': 'Берёзовые ступеньки',
  'minecraft:birch_trapdoor': 'Берёзовый люк',
  'minecraft:birch_wall_sign': 'Берёзовая настенная табличка',
  'minecraft:birch_wood': 'Берёза',
  'minecraft:black_banner': 'Чёрный флаг',
  'minecraft:black_bed': 'Чёрная кровать',
  'minecraft:black_carpet': 'Чёрный ковёр',
  'minecraft:black_concrete': 'Чёрный бетон',
  'minecraft:black_concrete_powder': 'Чёрный сухой бетон',
  'minecraft:black_glazed_terracotta': 'Чёрная глазурованная керамика',
  'minecraft:black_shulker_box': 'Чёрный шалкеровый ящик',
  'minecraft:black_stained_glass': 'Чёрное стекло',
  'minecraft:black_stained_glass_pane': 'Чёрная стеклянная панель',
  'minecraft:black_terracotta': 'Чёрная керамика',
  'minecraft:black_wool': 'Чёрная шерсть',
  'minecraft:blast_furnace': 'Плавильная печь',
  'minecraft:blue_banner': 'Синий флаг',
  'minecraft:blue_bed': 'Синяя кровать',
  'minecraft:blue_carpet': 'Синий ковёр',
  'minecraft:blue_concrete': 'Синий бетон',
  'minecraft:blue_concrete_powder': 'Синий сухой бетон',
  'minecraft:blue_glazed_terracotta': 'Синяя глазурованная керамика',
  'minecraft:blue_ice': 'Синий лёд',
  'minecraft:blue_orchid': 'Синяя орхидея',
  'minecraft:blue_shulker_box': 'Синий шалкеровый ящик',
  'minecraft:blue_stained_glass': 'Синее стекло',
  'minecraft:blue_stained_glass_pane': 'Синяя стеклянная панель',
  'minecraft:blue_terracotta': 'Синяя керамика',
  'minecraft:blue_wool': 'Синяя шерсть',
  'minecraft:bone_block': 'Костный блок',
  'minecraft:bookshelf': 'Книжная полка',
  'minecraft:brain_coral': 'Коралл-мозговик',
  'minecraft:brain_coral_block': 'Блок коралла-мозговика',
  'minecraft:brain_coral_fan': 'Веерный коралл-мозговик',
  'minecraft:brain_coral_wall_fan': 'Горизонтальный веерный коралл-мозговик',
  'minecraft:brewing_stand': 'Зельеварка',
  'minecraft:brick_slab': 'Кирпичная плита',
  'minecraft:brick_stairs': 'Кирпичные ступеньки',
  'minecraft:brick_wall': 'Кирпичная ограда',
  'minecraft:bricks': 'Кирпичи',
  'minecraft:brown_banner': 'Коричневый флаг',
  'minecraft:brown_bed': 'Коричневая кровать',
  'minecraft:brown_carpet': 'Коричневый ковёр',
  'minecraft:brown_concrete': 'Коричневый бетон',
  'minecraft:brown_concrete_powder': 'Коричневый сухой бетон',
  'minecraft:brown_glazed_terracotta': 'Коричневая глазурованная керамика',
  'minecraft:brown_mushroom': 'Коричневый гриб',
  'minecraft:brown_mushroom_block': 'Блок коричневого гриба',
  'minecraft:brown_shulker_box': 'Коричневый шалкеровый ящик',
  'minecraft:brown_stained_glass': 'Коричневое стекло',
  'minecraft:brown_stained_glass_pane': 'Коричневая стеклянная панель',
  'minecraft:brown_terracotta': 'Коричневая керамика',
  'minecraft:brown_wool': 'Коричневая шерсть',
  'minecraft:bubble_column': 'Колонна пузырей',
  'minecraft:bubble_coral': 'Пузырчатый коралл',
  'minecraft:bubble_coral_block': 'Блок пузырчатого коралла',
  'minecraft:bubble_coral_fan': 'Веерный пузырчатый коралл',
  'minecraft:bubble_coral_wall_fan': 'Горизонтальный веерный пузырчатый коралл',
  'minecraft:cactus': 'Кактус',
  'minecraft:cake': 'Торт',
  'minecraft:campfire': 'Костёр',
  'minecraft:carrots': 'Морковь',
  'minecraft:cartography_table': 'Стол картографа',
  'minecraft:carved_pumpkin': 'Вырезанная тыква',
  'minecraft:cauldron': 'Котёл',
  'minecraft:cave_air': 'Пещерный воздух',
  'minecraft:chain_command_block': 'Последовательный командный блок',
  'minecraft:chest': 'Сундук',
  'minecraft:chipped_anvil': 'Повреждённая наковальня',
  'minecraft:chiseled_quartz_block': 'Резной кварцевый блок',
  'minecraft:chiseled_red_sandstone': 'Резной красный песчаник',
  'minecraft:chiseled_sandstone': 'Резной песчаник',
  'minecraft:chiseled_stone_bricks': 'Резные каменные кирпичи',
  'minecraft:chorus_flower': 'Цветок хоруса',
  'minecraft:chorus_plant': 'Хорус',
  'minecraft:clay': 'Глина',
  'minecraft:coal_block': 'Угольный блок',
  'minecraft:coal_ore': 'Каменный уголь',
  'minecraft:coarse_dirt': 'Каменистая земля',
  'minecraft:cobblestone': 'Булыжник',
  'minecraft:cobblestone_slab': 'Булыжная плита',
  'minecraft:cobblestone_stairs': 'Булыжные ступеньки',
  'minecraft:cobblestone_wall': 'Булыжная ограда',
  'minecraft:cobweb': 'Паутина',
  'minecraft:cocoa': 'Какао',
  'minecraft:command_block': 'Командный блок',
  'minecraft:comparator': 'Редстоуновый компаратор',
  'minecraft:composter': 'Компостница',
  'minecraft:conduit': 'Морской источник',
  'minecraft:cornflower': 'Синий василёк',
  'minecraft:cracked_stone_bricks': 'Потрескавшиеся каменные кирпичи',
  'minecraft:crafting_table': 'Верстак',
  'minecraft:creeper_head': 'Голова крипера',
  'minecraft:creeper_wall_head': 'Настенная голова крипера',
  'minecraft:cut_red_sandstone': 'Пиленый красный песчаник',
  'minecraft:cut_red_sandstone_slab': 'Плита из пиленого красного песчаника',
  'minecraft:cut_sandstone': 'Пиленый песчаник',
  'minecraft:cut_sandstone_slab': 'Плита из пиленого песчаника',
  'minecraft:cyan_banner': 'Бирюзовый флаг',
  'minecraft:cyan_bed': 'Бирюзовая кровать',
  'minecraft:cyan_carpet': 'Бирюзовый ковёр',
  'minecraft:cyan_concrete': 'Бирюзовый бетон',
  'minecraft:cyan_concrete_powder': 'Бирюзовый сухой бетон',
  'minecraft:cyan_glazed_terracotta': 'Бирюзовая глазурованная керамика',
  'minecraft:cyan_shulker_box': 'Бирюзовый шалкеровый ящик',
  'minecraft:cyan_stained_glass': 'Бирюзовое стекло',
  'minecraft:cyan_stained_glass_pane': 'Бирюзовая стеклянная панель',
  'minecraft:cyan_terracotta': 'Бирюзовая керамика',
  'minecraft:cyan_wool': 'Бирюзовая шерсть',
  'minecraft:damaged_anvil': 'Разбитая наковальня',
  'minecraft:dandelion': 'Одуванчик',
  'minecraft:dark_oak_button': 'Кнопка из тёмного дуба',
  'minecraft:dark_oak_door': 'Дверь из тёмного дуба',
  'minecraft:dark_oak_fence': 'Забор из тёмного дуба',
  'minecraft:dark_oak_fence_gate': 'Калитка из тёмного дуба',
  'minecraft:dark_oak_leaves': 'Листья тёмного дуба',
  'minecraft:dark_oak_log': 'Бревно тёмного дуба',
  'minecraft:dark_oak_planks': 'Доски из тёмного дуба',
  'minecraft:dark_oak_pressure_plate': 'Нажимная плита из тёмного дуба',
  'minecraft:dark_oak_sapling': 'Саженец тёмного дуба',
  'minecraft:dark_oak_sign': 'Табличка из тёмного дуба',
  'minecraft:dark_oak_slab': 'Плита из тёмного дуба',
  'minecraft:dark_oak_stairs': 'Ступеньки из тёмного дуба',
  'minecraft:dark_oak_trapdoor': 'Люк из тёмного дуба',
  'minecraft:dark_oak_wall_sign': 'Настенная табличка из тёмного дуба',
  'minecraft:dark_oak_wood': 'Тёмный дуб',
  'minecraft:dark_prismarine': 'Тёмный призмарин',
  'minecraft:dark_prismarine_slab': 'Плита из тёмного призмарина',
  'minecraft:dark_prismarine_stairs': 'Ступеньки из тёмного призмарина',
  'minecraft:daylight_detector': 'Датчик дневного света',
  'minecraft:dead_brain_coral': 'Мёртвый коралл-мозговик',
  'minecraft:dead_brain_coral_block': 'Блок мёртвого коралла-мозговика',
  'minecraft:dead_brain_coral_fan': 'Мёртвый веерный коралл-мозговик',
  'minecraft:dead_brain_coral_wall_fan': 'Мёртвый горизонтальный веерный коралл-мозговик',
  'minecraft:dead_bubble_coral': 'Мёртвый пузырчатый коралл',
  'minecraft:dead_bubble_coral_block': 'Блок мёртвого пузырчатого коралла',
  'minecraft:dead_bubble_coral_fan': 'Мёртвый веерный пузырчатый коралл',
  'minecraft:dead_bubble_coral_wall_fan': 'Мёртвый горизонтальный веерный пузырчатый коралл',
  'minecraft:dead_bush': 'Мёртвый куст',
  'minecraft:dead_fire_coral': 'Мёртвый огненный коралл',
  'minecraft:dead_fire_coral_block': 'Блок мёртвого огненного коралла',
  'minecraft:dead_fire_coral_fan': 'Мёртвый веерный огненный коралл',
  'minecraft:dead_fire_coral_wall_fan': 'Мёртвый горизонтальный веерный огненный коралл',
  'minecraft:dead_horn_coral': 'Мёртвый роговый коралл',
  'minecraft:dead_horn_coral_block': 'Блок мёртвого рогового коралла',
  'minecraft:dead_horn_coral_fan': 'Мёртвый веерный роговый коралл',
  'minecraft:dead_horn_coral_wall_fan': 'Мёртвый горизонтальный веерный роговый коралл',
  'minecraft:dead_tube_coral': 'Мёртвый трубчатый коралл',
  'minecraft:dead_tube_coral_block': 'Блок мёртвого трубчатого коралла',
  'minecraft:dead_tube_coral_fan': 'Мёртвый веерный трубчатый коралл',
  'minecraft:dead_tube_coral_wall_fan': 'Мёртвый горизонтальный веерный трубчатый коралл',
  'minecraft:detector_rail': 'Рельсы с датчиком',
  'minecraft:diamond_block': 'Алмазный блок',
  'minecraft:diamond_ore': 'Алмазная руда',
  'minecraft:diorite': 'Диорит',
  'minecraft:diorite_slab': 'Диоритовая плита',
  'minecraft:diorite_stairs': 'Диоритовые ступеньки',
  'minecraft:diorite_wall': 'Диоритовая ограда',
  'minecraft:dirt': 'Земля',
  'minecraft:dispenser': 'Раздатчик',
  'minecraft:dragon_egg': 'Яйцо дракона',
  'minecraft:dragon_head': 'Голова дракона',
  'minecraft:dragon_wall_head': 'Настенная голова дракона',
  'minecraft:dried_kelp_block': 'Блок сушёной ламинарии',
  'minecraft:dropper': 'Выбрасыватель',
  'minecraft:emerald_block': 'Изумрудный блок',
  'minecraft:emerald_ore': 'Изумрудная руда',
  'minecraft:enchanting_table': 'Чародейский стол',
  'minecraft:end_gateway': 'Врата Энда',
  'minecraft:end_portal': 'Портал в Энд',
  'minecraft:end_portal_frame': 'Рамка портала в Энд',
  'minecraft:end_rod': 'Стержень Энда',
  'minecraft:end_stone': 'Эндерняк',
  'minecraft:end_stone_brick_slab': 'Плита из эндернякового кирпича',
  'minecraft:end_stone_brick_stairs': 'Ступеньки из эндернякового кирпича',
  'minecraft:end_stone_brick_wall': 'Ограда из эндернякового кирпича',
  'minecraft:end_stone_bricks': 'Эндерняковые кирпичи',
  'minecraft:ender_chest': 'Эндер-сундук',
  'minecraft:farmland': 'Пашня',
  'minecraft:fern': 'Папоротник',
  'minecraft:fire': 'Огонь',
  'minecraft:fire_coral': 'Огненный коралл',
  'minecraft:fire_coral_block': 'Блок огненного коралла',
  'minecraft:fire_coral_fan': 'Веерный огненный коралл',
  'minecraft:fire_coral_wall_fan': 'Горизонтальный веерный огненный коралл',
  'minecraft:fletching_table': 'Стол лучника',
  'minecraft:flower_pot': 'Цветочный горшок',
  'minecraft:flowing_lava': 'Текущая лава',
  'minecraft:flowing_water': 'Текущая вода',
  'minecraft:four_turtle_eggs': 'Четыре черепашьих яйца',
  'minecraft:frosted_ice': 'Талый лёд',
  'minecraft:furnace': 'Печь',
  'minecraft:glass': 'Стекло',
  'minecraft:glass_pane': 'Стеклянная панель',
  'minecraft:glowstone': 'Светокамень',
  'minecraft:gold_block': 'Золотой блок',
  'minecraft:gold_ore': 'Золотая руда',
  'minecraft:granite': 'Гранит',
  'minecraft:granite_slab': 'Гранитная плита',
  'minecraft:granite_stairs': 'Гранитные ступеньки',
  'minecraft:granite_wall': 'Гранитная ограда',
  'minecraft:grass': 'Трава',
  'minecraft:grass_block': 'Дёрн',
  'minecraft:grass_path': 'Тропа',
  'minecraft:gravel': 'Гравий',
  'minecraft:gray_banner': 'Серый флаг',
  'minecraft:gray_bed': 'Серая кровать',
  'minecraft:gray_carpet': 'Серый ковёр',
  'minecraft:gray_concrete': 'Серый бетон',
  'minecraft:gray_concrete_powder': 'Серый сухой бетон',
  'minecraft:gray_glazed_terracotta': 'Серая глазурованная керамика',
  'minecraft:gray_shulker_box': 'Серый шалкеровый ящик',
  'minecraft:gray_stained_glass': 'Серое стекло',
  'minecraft:gray_stained_glass_pane': 'Серая стеклянная панель',
  'minecraft:gray_terracotta': 'Серая керамика',
  'minecraft:gray_wool': 'Серая шерсть',
  'minecraft:green_banner': 'Зелёный флаг',
  'minecraft:green_bed': 'Зелёная кровать',
  'minecraft:green_carpet': 'Зелёный ковёр',
  'minecraft:green_concrete': 'Зелёный бетон',
  'minecraft:green_concrete_powder': 'Зелёный сухой бетон',
  'minecraft:green_glazed_terracotta': 'Зелёная глазурованная керамика',
  'minecraft:green_shulker_box': 'Зелёный шалкеровый ящик',
  'minecraft:green_stained_glass': 'Зелёное стекло',
  'minecraft:green_stained_glass_pane': 'Зелёная стеклянная панель',
  'minecraft:green_terracotta': 'Зелёная керамика',
  'minecraft:green_wool': 'Зелёная шерсть',
  'minecraft:grindstone': 'Точило',
  'minecraft:hay_block': 'Сноп сена',
  'minecraft:heavy_weighted_pressure_plate': 'Большегрузная весовая пластина',
  'minecraft:honey_block': 'Блок мёда',
  'minecraft:honeycomb_block': 'Блок пчелиных сот',
  'minecraft:hopper': 'Воронка',
  'minecraft:horn_coral': 'Роговой коралл',
  'minecraft:horn_coral_block': 'Блок рогового коралла',
  'minecraft:horn_coral_fan': 'Веерный роговый коралл',
  'minecraft:horn_coral_wall_fan': 'Горизонтальный веерный роговый коралл',
  'minecraft:ice': 'Лёд',
  'minecraft:infested_chiseled_stone_bricks': 'Заражённый резной каменный кирпич',
  'minecraft:infested_cobblestone': 'Заражённый булыжник',
  'minecraft:infested_cracked_stone_bricks': 'Заражённый потрескавшийся каменный кирпич',
  'minecraft:infested_mossy_stone_bricks': 'Заражённые замшелые каменные кирпичи',
  'minecraft:infested_stone': 'Заражённый камень',
  'minecraft:infested_stone_bricks': 'Заражённые каменные кирпичи',
  'minecraft:iron_bars': 'Железные прутья',
  'minecraft:iron_block': 'Железный блок',
  'minecraft:iron_door': 'Железная дверь',
  'minecraft:iron_ore': 'Железная руда',
  'minecraft:iron_trapdoor': 'Железный люк',
  'minecraft:jack_o_lantern': 'Светильник Джека',
  'minecraft:jigsaw': 'Пазл',
  'minecraft:jukebox': 'Проигрыватель',
  'minecraft:jungle_button': 'Кнопка из тропического дерева',
  'minecraft:jungle_door': 'Дверь из тропического дерева',
  'minecraft:jungle_fence': 'Забор из тропического дерева',
  'minecraft:jungle_fence_gate': 'Калитка из тропического дерева',
  'minecraft:jungle_leaves': 'Листья тропического дерева',
  'minecraft:jungle_log': 'Бревно тропического дерева',
  'minecraft:jungle_planks': 'Доски из тропического дерева',
  'minecraft:jungle_pressure_plate': 'Нажимная плита из тропического дерева',
  'minecraft:jungle_sapling': 'Саженец тропического дерева',
  'minecraft:jungle_sign': 'Табличка из тропического дерева',
  'minecraft:jungle_slab': 'Плита из тропического дерева',
  'minecraft:jungle_stairs': 'Ступеньки из тропического дерева',
  'minecraft:jungle_trapdoor': 'Люк из тропического дерева',
  'minecraft:jungle_wall_sign': 'Настенная табличка из тропического дерева',
  'minecraft:jungle_wood': 'Тропическое дерево',
  'minecraft:kelp': 'Ламинария',
  'minecraft:kelp_plant': 'Стебель ламинарии',
  'minecraft:ladder': 'Лестница',
  'minecraft:lantern': 'Фонарь',
  'minecraft:lapis_block': 'Лазуритовый блок',
  'minecraft:lapis_ore': 'Лазуритовая руда',
  'minecraft:large_fern': 'Раскидистый папоротник',
  'minecraft:lava': 'Лава',
  'minecraft:lectern': 'Кафедра',
  'minecraft:lever': 'Рычаг',
  'minecraft:light_blue_banner': 'Голубой флаг',
  'minecraft:light_blue_bed': 'Голубая кровать',
  'minecraft:light_blue_carpet': 'Голубой ковёр',
  'minecraft:light_blue_concrete': 'Голубой бетон',
  'minecraft:light_blue_concrete_powder': 'Голубой сухой бетон',
  'minecraft:light_blue_glazed_terracotta': 'Голубая глазурованная керамика',
  'minecraft:light_blue_shulker_box': 'Голубой шалкеровый ящик',
  'minecraft:light_blue_stained_glass': 'Голубое стекло',
  'minecraft:light_blue_stained_glass_pane': 'Голубая стеклянная панель',
  'minecraft:light_blue_terracotta': 'Голубая керамика',
  'minecraft:light_blue_wool': 'Голубая шерсть',
  'minecraft:light_gray_banner': 'Светло-серый флаг',
  'minecraft:light_gray_bed': 'Светло-серая кровать',
  'minecraft:light_gray_carpet': 'Светло-серый ковёр',
  'minecraft:light_gray_concrete': 'Светло-серый бетон',
  'minecraft:light_gray_concrete_powder': 'Светло-серый сухой бетон',
  'minecraft:light_gray_glazed_terracotta': 'Светло-серая глазурованная керамика',
  'minecraft:light_gray_shulker_box': 'Светло-серый шалкеровый ящик',
  'minecraft:light_gray_stained_glass': 'Светло-серое стекло',
  'minecraft:light_gray_stained_glass_pane': 'Светло-серая стеклянная панель',
  'minecraft:light_gray_terracotta': 'Светло-серая керамика',
  'minecraft:light_gray_wool': 'Светло-серая шерсть',
  'minecraft:light_weighted_pressure_plate': 'Весовая пластина',
  'minecraft:lilac': 'Сирень',
  'minecraft:lily_of_the_valley': 'Ландыш',
  'minecraft:lily_pad': 'Кувшинка',
  'minecraft:lime_banner': 'Лаймовый флаг',
  'minecraft:lime_bed': 'Лаймовая кровать',
  'minecraft:lime_carpet': 'Лаймовый ковёр',
  'minecraft:lime_concrete': 'Лаймовый бетон',
  'minecraft:lime_concrete_powder': 'Лаймовый сухой бетон',
  'minecraft:lime_glazed_terracotta': 'Лаймовая глазурованная керамика',
  'minecraft:lime_shulker_box': 'Лаймовый шалкеровый ящик',
  'minecraft:lime_stained_glass': 'Лаймовое стекло',
  'minecraft:lime_stained_glass_pane': 'Лаймовая стеклянная панель',
  'minecraft:lime_terracotta': 'Лаймовая керамика',
  'minecraft:lime_wool': 'Лаймовая шерсть',
  'minecraft:loom': 'Ткацкий станок',
  'minecraft:magenta_banner': 'Пурпурный флаг',
  'minecraft:magenta_bed': 'Пурпурная кровать',
  'minecraft:magenta_carpet': 'Пурпурный ковёр',
  'minecraft:magenta_concrete': 'Пурпурный бетон',
  'minecraft:magenta_concrete_powder': 'Пурпурный сухой бетон',
  'minecraft:magenta_glazed_terracotta': 'Пурпурная глазурованная керамика',
  'minecraft:magenta_shulker_box': 'Пурпурный шалкеровый ящик',
  'minecraft:magenta_stained_glass': 'Пурпурное стекло',
  'minecraft:magenta_stained_glass_pane': 'Пурпурная стеклянная панель',
  'minecraft:magenta_terracotta': 'Пурпурная керамика',
  'minecraft:magenta_wool': 'Пурпурная шерсть',
  'minecraft:magma_block': 'Магма',
  'minecraft:melon': 'Арбуз',
  'minecraft:melon_stem': 'Стебель арбуза',
  'minecraft:mossy_cobblestone': 'Замшелый булыжник',
  'minecraft:mossy_cobblestone_slab': 'Замшелая булыжная плита',
  'minecraft:mossy_cobblestone_stairs': 'Замшелые булыжные ступеньки',
  'minecraft:mossy_cobblestone_wall': 'Замшелая булыжная ограда',
  'minecraft:mossy_stone_brick_slab': 'Плита из замшелого каменного кирпича',
  'minecraft:mossy_stone_brick_stairs': 'Ступеньки из замшелого каменного кирпича',
  'minecraft:mossy_stone_brick_wall': 'Ограда из замшелого каменного кирпича',
  'minecraft:mossy_stone_bricks': 'Замшелые каменные кирпичи',
  'minecraft:moving_piston': 'Движущийся поршень',
  'minecraft:mushroom_stem': 'Ножка гриба',
  'minecraft:mycelium': 'Мицелий',
  'minecraft:nether_brick_fence': 'Незерский забор',
  'minecraft:nether_brick_slab': 'Незерская плита',
  'minecraft:nether_brick_stairs': 'Незерские ступеньки',
  'minecraft:nether_brick_wall': 'Ограда из незерского кирпича',
  'minecraft:nether_bricks': 'Незерские кирпичи',
  'minecraft:nether_portal': 'Портал в Незер',
  'minecraft:nether_quartz_ore': 'Незер-кварцевая руда',
  'minecraft:nether_wart': 'Нарост из Незера',
  'minecraft:nether_wart_block': 'Блок нароста из Незера',
  'minecraft:netherrack': 'Незерак',
  'minecraft:note_block': 'Нотный блок',
  'minecraft:oak_button': 'Дубовая кнопка',
  'minecraft:oak_door': 'Дубовая дверь',
  'minecraft:oak_fence': 'Дубовый забор',
  'minecraft:oak_fence_gate': 'Дубовая калитка',
  'minecraft:oak_leaves': 'Дубовые листья',
  'minecraft:oak_log': 'Дубовое бревно',
  'minecraft:oak_planks': 'Дубовые доски',
  'minecraft:oak_pressure_plate': 'Дубовая нажимная плита',
  'minecraft:oak_sapling': 'Саженец дуба',
  'minecraft:oak_sign': 'Дубовая табличка',
  'minecraft:oak_slab': 'Дубовая плита',
  'minecraft:oak_stairs': 'Дубовые ступеньки',
  'minecraft:oak_trapdoor': 'Дубовый люк',
  'minecraft:oak_wall_sign': 'Дубовая настенная табличка',
  'minecraft:oak_wood': 'Дуб',
  'minecraft:observer': 'Наблюдатель',
  'minecraft:obsidian': 'Обсидиан',
  'minecraft:ominous_banner': 'Зловещий флаг',
  'minecraft:orange_banner': 'Оранжевый флаг',
  'minecraft:orange_bed': 'Оранжевая кровать',
  'minecraft:orange_carpet': 'Оранжевый ковёр',
  'minecraft:orange_concrete': 'Оранжевый бетон',
  'minecraft:orange_concrete_powder': 'Оранжевый сухой бетон',
  'minecraft:orange_glazed_terracotta': 'Оранжевая глазурованная керамика',
  'minecraft:orange_shulker_box': 'Оранжевый шалкеровый ящик',
  'minecraft:orange_stained_glass': 'Оранжевое стекло',
  'minecraft:orange_stained_glass_pane': 'Оранжевая стеклянная панель',
  'minecraft:orange_terracotta': 'Оранжевая керамика',
  'minecraft:orange_tulip': 'Оранжевый тюльпан',
  'minecraft:orange_wool': 'Оранжевая шерсть',
  'minecraft:oxeye_daisy': 'Ромашка',
  'minecraft:packed_ice': 'Плотный лёд',
  'minecraft:peony': 'Пион',
  'minecraft:petrified_oak_slab': 'Окаменевшая дубовая плита',
  'minecraft:pink_banner': 'Розовый флаг',
  'minecraft:pink_bed': 'Розовая кровать',
  'minecraft:pink_carpet': 'Розовый ковёр',
  'minecraft:pink_concrete': 'Розовый бетон',
  'minecraft:pink_concrete_powder': 'Розовый сухой бетон',
  'minecraft:pink_glazed_terracotta': 'Розовая глазурованная керамика',
  'minecraft:pink_shulker_box': 'Розовый шалкеровый ящик',
  'minecraft:pink_stained_glass': 'Розовое стекло',
  'minecraft:pink_stained_glass_pane': 'Розовая стеклянная панель',
  'minecraft:pink_terracotta': 'Розовая керамика',
  'minecraft:pink_tulip': 'Розовый тюльпан',
  'minecraft:pink_wool': 'Розовая шерсть',
  'minecraft:piston': 'Поршень',
  'minecraft:piston_head': 'Головка поршня',
  'minecraft:player_head': 'Голова игрока',
  'minecraft:player_wall_head': 'Настенная голова игрока',
  'minecraft:podzol': 'Подзол',
  'minecraft:polished_andesite': 'Полированный андезит',
  'minecraft:polished_andesite_slab': 'Плита из полированного андезита',
  'minecraft:polished_andesite_stairs': 'Ступеньки из полированного андезита',
  'minecraft:polished_diorite': 'Полированный диорит',
  'minecraft:polished_diorite_slab': 'Плита из полированного диорита',
  'minecraft:polished_diorite_stairs': 'Ступеньки из полированного диорита',
  'minecraft:polished_granite': 'Полированный гранит',
  'minecraft:polished_granite_slab': 'Плита из полированного гранита',
  'minecraft:polished_granite_stairs': 'Ступеньки из полированного гранита',
  'minecraft:poppy': 'Мак',
  'minecraft:potatoes': 'Картофель',
  'minecraft:potted_acacia_sapling': 'Саженец акации в горшке',
  'minecraft:potted_allium': 'Лук-батун в горшке',
  'minecraft:potted_azure_bluet': 'Хаустония серая в горшке',
  'minecraft:potted_bamboo': 'Бамбук в горшке',
  'minecraft:potted_birch_sapling': 'Саженец берёзы в горшке',
  'minecraft:potted_blue_orchid': 'Синяя орхидея в горшке',
  'minecraft:potted_brown_mushroom': 'Коричневый гриб в горшке',
  'minecraft:potted_cactus': 'Кактус в горшке',
  'minecraft:potted_cornflower': 'Синий василёк в горшке',
  'minecraft:potted_dandelion': 'Одуванчик в горшке',
  'minecraft:potted_dark_oak_sapling': 'Саженец тёмного дуба в горшке',
  'minecraft:potted_dead_bush': 'Мёртвый куст в горшке',
  'minecraft:potted_fern': 'Папортник в горшке',
  'minecraft:potted_jungle_sapling': 'Саженец тропического дерева в горшке',
  'minecraft:potted_lily_of_the_valley': 'Ландыш в горшке',
  'minecraft:potted_oak_sapling': 'Саженец дуба в горшке',
  'minecraft:potted_orange_tulip': 'Оранжевый тюльпан в горшке',
  'minecraft:potted_oxeye_daisy': 'Ромашка в горшке',
  'minecraft:potted_pink_tulip': 'Розовый тюльпан в горшке',
  'minecraft:potted_poppy': 'Мак в горшке',
  'minecraft:potted_red_mushroom': 'Красный гриб в горшке',
  'minecraft:potted_red_tulip': 'Красный тюльпан в горшке',
  'minecraft:potted_spruce_sapling': 'Саженец ели в горшке',
  'minecraft:potted_white_tulip': 'Белый тюльпан в горшке',
  'minecraft:potted_wither_rose': 'Роза визера в горшке',
  'minecraft:powered_rail': 'Энергорельсы',
  'minecraft:prismarine': 'Призмарин',
  'minecraft:prismarine_brick_slab': 'Плита из призмаринового кирпича',
  'minecraft:prismarine_brick_stairs': 'Ступеньки из призмариновых кирпичей',
  'minecraft:prismarine_bricks': 'Призмариновые кирпичи',
  'minecraft:prismarine_slab': 'Призмариновая плита',
  'minecraft:prismarine_stairs': 'Призмариновые ступеньки',
  'minecraft:prismarine_wall': 'Призмариновая ограда',
  'minecraft:pumpkin': 'Тыква',
  'minecraft:pumpkin_stem': 'Стебель тыквы',
  'minecraft:purple_banner': 'Фиолетовый флаг',
  'minecraft:purple_bed': 'Фиолетовая кровать',
  'minecraft:purple_carpet': 'Фиолетовый ковёр',
  'minecraft:purple_concrete': 'Фиолетовый бетон',
  'minecraft:purple_concrete_powder': 'Фиолетовый сухой бетон',
  'minecraft:purple_glazed_terracotta': 'Фиолетовая глазурованная керамика',
  'minecraft:purple_shulker_box': 'Фиолетовый шалкеровый ящик',
  'minecraft:purple_stained_glass': 'Фиолетовое стекло',
  'minecraft:purple_stained_glass_pane': 'Фиолетовая стеклянная панель',
  'minecraft:purple_terracotta': 'Фиолетовая керамика',
  'minecraft:purple_wool': 'Фиолетовая шерсть',
  'minecraft:purpur_block': 'Пурпур',
  'minecraft:purpur_pillar': 'Пурпуровый пилон',
  'minecraft:purpur_slab': 'Пурпуровая плита',
  'minecraft:purpur_stairs': 'Пурпуровые ступеньки',
  'minecraft:quartz_block': 'Кварцевый блок',
  'minecraft:quartz_pillar': 'Кварцевая колонна',
  'minecraft:quartz_slab': 'Кварцевая плита',
  'minecraft:quartz_stairs': 'Кварцевые ступеньки',
  'minecraft:rail': 'Рельсы',
  'minecraft:red_banner': 'Красный флаг',
  'minecraft:red_bed': 'Красная кровать',
  'minecraft:red_carpet': 'Красный ковёр',
  'minecraft:red_concrete': 'Красный бетон',
  'minecraft:red_concrete_powder': 'Красный сухой бетон',
  'minecraft:red_glazed_terracotta': 'Красная глазурованная керамика',
  'minecraft:red_mushroom': 'Красный гриб',
  'minecraft:red_mushroom_block': 'Блок красного гриба',
  'minecraft:red_nether_brick_slab': 'Плита из красного незерского кирпича',
  'minecraft:red_nether_brick_stairs': 'Ступеньки из красного незерского кирпича',
  'minecraft:red_nether_brick_wall': 'Ограда из красного незерского кирпича',
  'minecraft:red_nether_bricks': 'Красные незерские кирпичи',
  'minecraft:red_sand': 'Красный песок',
  'minecraft:red_sandstone': 'Красный песчаник',
  'minecraft:red_sandstone_slab': 'Плита из красного песчаника',
  'minecraft:red_sandstone_stairs': 'Ступеньки из красного песчаника',
  'minecraft:red_sandstone_wall': 'Ограда из красного песчаника',
  'minecraft:red_shulker_box': 'Красный шалкеровый ящик',
  'minecraft:red_stained_glass': 'Красное стекло',
  'minecraft:red_stained_glass_pane': 'Красная стеклянная панель',
  'minecraft:red_terracotta': 'Красная керамика',
  'minecraft:red_tulip': 'Красный тюльпан',
  'minecraft:red_wool': 'Красная шерсть',
  'minecraft:redstone_block': 'Редстоуновый блок',
  'minecraft:redstone_lamp': 'Редстоуновый фонарь',
  'minecraft:redstone_ore': 'Редстоуновая руда',
  'minecraft:redstone_torch': 'Редстоуновый факел',
  'minecraft:redstone_wall_torch': 'Настенный редстоуновый факел',
  'minecraft:redstone_wire': 'Редстоуновый провод',
  'minecraft:repeater': 'Редстоуновый повторитель',
  'minecraft:repeating_command_block': 'Повторяющий командный блок',
  'minecraft:rose_bush': 'Розовый куст',
  'minecraft:sand': 'Песок',
  'minecraft:sandstone': 'Песчаник',
  'minecraft:sandstone_slab': 'Песчаниковая плита',
  'minecraft:sandstone_stairs': 'Песчаниковые ступеньки',
  'minecraft:sandstone_wall': 'Песчаниковая ограда',
  'minecraft:scaffolding': 'Подмостки',
  'minecraft:sea_lantern': 'Морской фонарь',
  'minecraft:sea_pickle': 'Морской огурец',
  'minecraft:seagrass': 'Морская трава',
  'minecraft:shulker_box': 'Шалкеровый ящик',
  'minecraft:skeleton_skull': 'Череп',
  'minecraft:skeleton_wall_skull': 'Настенный череп скелета',
  'minecraft:slime_block': 'Блок слизи',
  'minecraft:smithing_table': 'Стол кузнеца',
  'minecraft:smoker': 'Коптильня',
  'minecraft:smooth_quartz': 'Гладкий кварц',
  'minecraft:smooth_quartz_slab': 'Плита из гладкого кварца',
  'minecraft:smooth_quartz_stairs': 'Ступеньки из гладкого кварца',
  'minecraft:smooth_red_sandstone': 'Гладкий красный песчаник',
  'minecraft:smooth_red_sandstone_slab': 'Плита из гладкого красного песчаника',
  'minecraft:smooth_red_sandstone_stairs': 'Ступеньки из гладкого красного песчаника',
  'minecraft:smooth_sandstone': 'Гладкий песчаник',
  'minecraft:smooth_sandstone_slab': 'Плита из гладкого песчаника',
  'minecraft:smooth_sandstone_stairs': 'Ступеньки из гладкого песчаника',
  'minecraft:smooth_stone': 'Гладкий камень',
  'minecraft:smooth_stone_slab': 'Плита из гладкого камня',
  'minecraft:snow': 'Снег',
  'minecraft:snow_block': 'Блок снега',
  'minecraft:soul_sand': 'Песок душ',
  'minecraft:spawner': 'Рассадник',
  'minecraft:sponge': 'Губка',
  'minecraft:spruce_button': 'Еловая кнопка',
  'minecraft:spruce_door': 'Еловая дверь',
  'minecraft:spruce_fence': 'Еловый забор',
  'minecraft:spruce_fence_gate': 'Еловая калитка',
  'minecraft:spruce_leaves': 'Хвоя',
  'minecraft:spruce_log': 'Еловое бревно',
  'minecraft:spruce_planks': 'Еловые доски',
  'minecraft:spruce_pressure_plate': 'Еловая нажимная плита',
  'minecraft:spruce_sapling': 'Еловый саженец',
  'minecraft:spruce_sign': 'Еловая табличка',
  'minecraft:spruce_slab': 'Еловая плита',
  'minecraft:spruce_stairs': 'Еловые ступеньки',
  'minecraft:spruce_trapdoor': 'Еловый люк',
  'minecraft:spruce_wall_sign': 'Еловая настенная табличка',
  'minecraft:spruce_wood': 'Ель',
  'minecraft:sticky_piston': 'Липкий поршень',
  'minecraft:stone': 'Камень',
  'minecraft:stone_brick_slab': 'Плита из каменного кирпича',
  'minecraft:stone_brick_stairs': 'Ступеньки из каменного кирпича',
  'minecraft:stone_brick_wall': 'Ограда из каменного кирпича',
  'minecraft:stone_bricks': 'Каменные кирпичи',
  'minecraft:stone_button': 'Каменная кнопка',
  'minecraft:stone_pressure_plate': 'Каменная нажимная плита',
  'minecraft:stone_slab': 'Каменная плита',
  'minecraft:stone_stairs': 'Каменные ступеньки',
  'minecraft:stonecutter': 'Камнерез',
  'minecraft:stripped_acacia_log': 'Обтёсанное акациевое бревно',
  'minecraft:stripped_acacia_wood': 'Обтёсанная акациевая древесина',
  'minecraft:stripped_birch_log': 'Обтёсанное берёзовое бревно',
  'minecraft:stripped_birch_wood': 'Обтёсанная берёзовая древесина',
  'minecraft:stripped_dark_oak_log': 'Обтёсанное бревно тёмного дуба',
  'minecraft:stripped_dark_oak_wood': 'Обтёсанная древесина тёмного дуба',
  'minecraft:stripped_jungle_log': 'Обтёсанное бревно тропического дерева',
  'minecraft:stripped_jungle_wood': 'Обтёсанная тропическая древесина',
  'minecraft:stripped_oak_log': 'Обтёсанное дубовое бревно',
  'minecraft:stripped_oak_wood': 'Обтёсанная дубовая древесина',
  'minecraft:stripped_spruce_log': 'Обтёсанное еловое бревно',
  'minecraft:stripped_spruce_wood': 'Обтёсанная еловая древесина',
  'minecraft:structure_block': 'Блок-конструктор',
  'minecraft:structure_void': 'Пустой блок',
  'minecraft:sugar_cane': 'Сахарный тростник',
  'minecraft:sunflower': 'Подсолнух',
  'minecraft:sweet_berry_bush': 'Куст сладких ягод',
  'minecraft:tall_grass': 'Высокая трава',
  'minecraft:tall_seagrass': 'Высокая морская трава',
  'minecraft:terracotta': 'Терракота',
  'minecraft:three_turtle_eggs': 'Три черепашьих яйца',
  'minecraft:tnt': 'Динамит',
  'minecraft:torch': 'Факел',
  'minecraft:trapped_chest': 'Сундук-ловушка',
  'minecraft:tripwire': 'Растяжка',
  'minecraft:tripwire_hook': 'Крюк',
  'minecraft:tube_coral': 'Трубчатый коралл',
  'minecraft:tube_coral_block': 'Блок трубчатого коралла',
  'minecraft:tube_coral_fan': 'Веерный трубчатый коралл',
  'minecraft:tube_coral_wall_fan': 'Горизонтальный веерный трубчатый коралл',
  'minecraft:turtle_egg': 'Черепашье яйцо',
  'minecraft:two_turtle_eggs': 'Два черепашьих яйца',
  'minecraft:vine': 'Лианы',
  'minecraft:void_air': 'Вакуум',
  'minecraft:wall_banner': 'Настенный флаг',
  'minecraft:wall_torch': 'Настенный факел',
  'minecraft:water': 'Вода',
  'minecraft:wet_sponge': 'Мокрая губка',
  'minecraft:wheat': 'Ростки пшеницы',
  'minecraft:white_banner': 'Белый флаг',
  'minecraft:white_bed': 'Белая кровать',
  'minecraft:white_carpet': 'Белый ковёр',
  'minecraft:white_concrete': 'Белый бетон',
  'minecraft:white_concrete_powder': 'Белый сухой бетон',
  'minecraft:white_glazed_terracotta': 'Белая глазурованная керамика',
  'minecraft:white_shulker_box': 'Белый шалкеровый ящик',
  'minecraft:white_stained_glass': 'Белое стекло',
  'minecraft:white_stained_glass_pane': 'Белая стеклянная панель',
  'minecraft:white_terracotta': 'Белая керамика',
  'minecraft:white_tulip': 'Белый тюльпан',
  'minecraft:white_wool': 'Белая шерсть',
  'minecraft:wither_rose': 'Роза визера',
  'minecraft:wither_skeleton_skull': 'Череп визер-скелета',
  'minecraft:wither_skeleton_wall_skull': 'Настенный череп визер-скелета',
  'minecraft:yellow_banner': 'Жёлтый флаг',
  'minecraft:yellow_bed': 'Жёлтая кровать',
  'minecraft:yellow_carpet': 'Жёлтый ковёр',
  'minecraft:yellow_concrete': 'Жёлтый бетон',
  'minecraft:yellow_concrete_powder': 'Жёлтый сухой бетон',
  'minecraft:yellow_glazed_terracotta': 'Жёлтая глазурованная керамика',
  'minecraft:yellow_shulker_box': 'Жёлтый шалкеровый ящик',
  'minecraft:yellow_stained_glass': 'Жёлтое стекло',
  'minecraft:yellow_stained_glass_pane': 'Жёлтая стеклянная панель',
  'minecraft:yellow_terracotta': 'Жёлтая керамика',
  'minecraft:yellow_wool': 'Жёлтая шерсть',
  'minecraft:zombie_head': 'Голова зомби',
  'minecraft:zombie_wall_head': 'Настенная голова зомби',
};

export function getString(value: string) {
  if (strings[value] !== undefined && strings[value] !== '') {
    return strings[value];
  }

  return `${config.get('undefinedTextWrapper')}${value}${config.get('undefinedTextWrapper')}`;
}
